export const MONTHS_GENITIVE = [
  'янв', 'фев', 'мар', 'апр',
  'мая', 'июн', 'июл', 'авг',
  'сен', 'окт', 'ноя', 'дек'
]

export const MONTHS_FULL = [
  'Январь', 'Февраль', 'Март', 'Апрель',
  'Май', 'Июнь', 'Июль', 'Август',
  'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'
]


export const TIME_OPTIONS = [
  {title: '00:00', status: 'inactive'},
  {title: '01:00', status: 'inactive'},
  {title: '02:00', status: 'inactive'},
  {title: '03:00', status: 'inactive'},
  {title: '04:00', status: 'default'},
  {title: '05:00', status: 'inactive'},
  {title: '06:00', status: 'default'},
  {title: '07:00', status: 'default'},
  {title: '08:00', status: 'default'},
  {title: '09:00', status: 'default'},
  {title: '10:00', status: 'active'},
  {title: '11:00', status: 'default'},
  {title: '12:00', status: 'default'},
  {title: '13:00', status: 'active'},
  {title: '14:00', status: 'active'},
  {title: '15:00', status: 'default'},
  {title: '16:00', status: 'default'},
  {title: '17:00', status: 'default'},
  {title: '18:00', status: 'inactive'},
  {title: '19:00', status: 'inactive'},
  {title: '20:00', status: 'inactive'},
  {title: '21:00', status: 'inactive'},
  {title: '22:00', status: 'inactive'},
  {title: '23:00', status: 'inactive'}
]



export const months = [
  {title: 'Июнь', status: 'active'},
  {title: 'Июль', status: 'ready'},
  {title: 'Август', status: 'ready'},
  {title: 'Сентябрь', status: 'inactive'},
  {title: 'Октябрь', status: 'inactive'},
  {title: 'Ноябрь', status: 'inactive'},
  {title: 'Декабрь', status: 'inactive'},
  {title: 'Январь', status: 'inactive'},
  {title: 'Февраль', status: 'inactive'},
  {title: 'Март', status: 'inactive'},
  {title: 'Апрель', status: 'inactive'},
  {title: 'Май', status: 'inactive'},
]

export const plugins = [
  {id: 1, label: 'FabFilter', childrens: [
    'Pro-Q3',
    'Pro-Q4',
    'Pro-C',
    'Pro-DS',
    'Pro-MB',
    'Pro-G',
    'Pro-R2',
    'Pro-L2',
    'Saturn 2',
    'Simplon',
    'Timeless 3',
    'Volcano 3',
  ]},
  {id: 2, label: 'Waves', childrens: [
    'Abbey Road Saturator',
    'C6 Stereo',
    'C6-SideChain',
    'CLA Effects',
    'CLA-2A',
    'CLA-3A',
    'CLA-76',
    'Clarity Vx',
    'Clarity Vx Pro',
    'Clarity Vx - Dereverb',
    'Clarity Vx - Dereverb Pro',
    'DeEsser',
    'Doubler2',
    'Doubler4',
    'H-Delay',
    'IDX Intelligent Dynamics',
    'IDX LIVE Intelligent Dynamics',
    'Maserati GRP',
    'MetaFlanger',
    'NS1',
    'OVox',
    'PuigTec EQP1A',
    'PuigTec MEQ5',
    'RVox',
    'Sibilance',
    'Sibilance-Live',
    'SoundShifter Pitch',
    'SSL EV2 Channel',
    'SSLChannel',
    'SSLComp',
    'SSLEQ',
    'UltraPitch 3 Voices',
    'UltraPitch 6 Voices',
    'Vocal Bender',
    'Waves Tune Real-Time',
  ]},
  {id: 3, label: 'Valhalla DSP', childrens: [
    'ValhallaDelay',
    'ValhallaFreqEcho',
    'ValhallaFutureVerb',
    'ValhallaShimmer',
    'ValhallaSpaceMod',
    'ValhallaSpaceModulator',
    'ValhallaSupermassive',
    'ValhallaUberMod',
    'ValhallaVintageVerb',
  ]},
  {id: 4, label: 'Plugin Alliance', childrens: [
    'bx_delay2500',
    'bx_opto',
    'elysia alpha master',
    'elysia alpha master_2',
    'elysia alpha mix',
    'elysia karacter master',
    'elysia karacter mix',
    'elysia mpressor',
    'elysia mpressor sc',
    'elysia museq master',
    'elysia museq mix',
    'elysia niveau filter',
    'elysia nvelope',
    'elysia phils cascade',
    'Kilve Xtressor',
    'Maag EQ2',
    'Maag EQ4',
    'Maag MAGNUM-K',
    'TBTECH Cenozoix Compressor',
    'Vertigo VSM-3',
  ]},
  {id: 5, label: 'Universal Audio', childrens: [
    '1176 Classic Limiter Collection',
    '1176LN Rev E',
    '1176SE',
    'API 550A',
    'API 560',
    'API 2500',
    'Capitol Chambers',
    'EMT 140 Classic Plate Reverb',
    'Empirical Labs Distressor',
    'Galaxy Tape Echo',
    'Lexicon 224 Digital Reverb',
    'Manley Massive Passive EQ',
    'Neve 1073 Preamp & EQ',
    'Neve 1084 Preamp & EQ',
    'Neve 33609 Compressor',
    'Pultec EQP-1A',
    'Pultec MEQ-5',
    'SSL E Channel Strip',
    'SSL G Bus Compressor',
    'Teletronix LA-2A',
    'Teletronix LA-3A',
  ]},
  {id: 6, label: 'Kilohearts', childrens: [
    'Disperser',
    'Faturator',
    'Multipass',
    'Phase Distortion',
    'Reverser',
    'Snap Heap',
    'Stereo',
    'Trance Gate',
  ]},
  {id: 7, label: 'Antares', childrens: [
    'Auto-Tune Pro',
    'Auto-Tune Artist',
    'Auto-Tune EFX+',
    'Auto-Tune Slice',
    'Auto-Tune Vocal Compressor',
    'Auto-Tune Vocal EQ',
    'MUTATOR EVO',
    'Throat EVO',
  ]},
  {id: 8, label: 'iZotope', childrens: [
    'Nectar 4',
    'Neoverb',
    'Neutron 4',
    'Ozone 11',
    'RX 11 De-click',
    'RX 11 De-hum',
    'RX 11 De-noise',
    'RX 11 Mouth De-click',
    'RX 11 Spectral De-noise',
    'RX 11 Voice De-noise',
    'Stutter Edit 2',
    'Trash 2',
    'VocalSynth 2',
  ]},
  {id: 9, label: 'Soundtoys', childrens: [
    'Crystallizer',
    'Decapitator',
    'EchoBoy',
    'FilterFreak',
    'Little AlterBoy',
    'Little Plate',
    'MicroShift',
    'PanMan',
    'PhaseMistress',
    'PrimalTap',
    'Radiator',
  ]},
  {id: 10, label: 'Arturia', childrens: [
    'Comp DIODE-609',
    'Comp FET-76',
    'Comp TUBE-STA',
    'Comp VCA-65',
    'Delay TAPE-201',
    'EQ SITRAL-295',
    'Flanger BL-20',
    'Pre 1973',
    'Pre TridA',
    'Rev INTENSITY',
    'Rev PLATE-140',
    'Rev SPRING-636',
  ]},
  {id: 11, label: 'Native Instruments', childrens: [
    'Guitar Rig 7 Pro',
    'Kontakt 7',
    'Massive X',
    'Reaktor 6',
    'Replika XT',
    'Reverb Classics',
    'Solid Bus Comp',
    'Solid Dynamics',
    'Solid EQ',
    'Supercharger GT',
    'The Gentleman',
    'The Mouth',
  ]},
  {id: 12, label: 'Slate Digital', childrens: [
    'FG-X Virtual Mastering Processor',
    'Fresh Air',
    'Infinity EQ',
    'Monster',
    'Repeater',
    'Revival',
    'Virtual Buss Compressors',
    'Virtual Channel',
    'Virtual Mix Rack',
    'Virtual Tape Machines',
  ]},
  {id: 13, label: 'Softube', childrens: [
    'Console 1',
    'Drawmer 1973',
    'Saturn 2',
    'Tape',
    'TSAR-1 Reverb',
    'Tube Delay',
    'Weiss Deess',
    'Weiss DS1-MK3',
    'Weiss MM-1',
  ]},
  {id: 14, label: 'Eventide', childrens: [
    'Anthology XII',
    'Blackhole',
    'CrushStation',
    'H3000 Factory',
    'H910 Harmonizer',
    'Octavox',
    'Quadravox',
    'Shimmerverb',
    'Tverb',
    'UltraReverb',
  ]},
  {id: 15, label: 'McDSP', childrens: [
    '4020 Retro EQ',
    '4030 Retro Compressor',
    '6050 Ultimate Channel Strip',
    'AE400 Active EQ',
    'Analog Channel',
    'Channel G',
    'Compressor Bank',
    'FilterBank',
    'FutzBox',
    'Revolver',
  ]},
  {id: 16, label: 'Melda Production', childrens: [
    'MDynamics',
    'MAutoPitch',
    'MCompressor',
    'MConvolutionEZ',
    'MDelay',
    'MDynamicEQ',
    'MEqualizer',
    'MMultiBandCompressor',
    'MReverb',
    'MStereoExpander',
    'MTransformer',
    'MTurboReverb',
  ]},
  {id: 17, label: 'Acustica Audio', childrens: [
    'Acqua',
    'Amethyst',
    'Aquamarine',
    'Azure',
    'Coral2',
    'Cream',
    'Diamond',
    'Ebony',
    'Gold 3',
    'Magenta 4',
    'Titanium',
  ]},
  {id: 18, label: 'Tokyo Dawn Labs', childrens: [
    'Kotelnikov',
    'Nova',
    'SlickEQ',
    'TDR Molot',
    'TDR Molotok',
    'TDR Prism',
    'TDR VOS SlickEQ',
    'VladG Limiter No6',
  ]},
  {id: 19, label: 'Kush Audio', childrens: [
    'Clariphonic DSP',
    'Electra DSP',
    'Novatron',
    'Omega N',
    'Omega TWK',
    'Pusher',
    'Reddi',
    'UBK-1',
  ]},
  {id: 20, label: 'PSP Audioware', childrens: [
    '2445 EMT',
    '608 MultiDelay',
    '85 Delay',
    'Lexicon PSP 42',
    'MasterComp',
    'MicroWarmer',
    'Oldtimer',
    'VintageWarmer2',
  ]},
]
